"""Original background music for The Sky Princess, synthesized from scratch.

Two seamless loops:
  menu.mp3  "Moonlit Court"  - calm harp, celesta and warm strings pad
  game.mp3  "Starlit Steps"  - lighter, brighter, with soft pulse and pizzicato bass

Everything here is generated by code, so the music belongs to the project.
Usage: python3 tools/compose_music.py   (needs numpy and ffmpeg)
"""
import subprocess
import numpy as np

SR = 44100
rng = np.random.default_rng(7)


def midi(n):
    return 440.0 * 2 ** ((n - 69) / 12)


def env_adsr(n, a, d, s, r, sr=SR):
    a, d, r = int(a * sr), int(d * sr), int(r * sr)
    e = np.full(n, s, dtype=np.float64)
    a = min(a, n)
    e[:a] = np.linspace(0, 1, a, endpoint=False)
    d_end = min(a + d, n)
    e[a:d_end] = np.linspace(1, s, d_end - a, endpoint=False)
    if r > 0 and n > r:
        e[-r:] *= np.linspace(1, 0, r)
    return e


def harp(freq, dur, vel=1.0):
    """Plucked string: harmonics that decay faster the higher they are."""
    n = int(dur * SR)
    t = np.arange(n) / SR
    out = np.zeros(n)
    for k in range(1, 9):
        f = freq * k * (1 + 0.0004 * k * k)  # slight stiffness
        if f > SR / 2.2:
            break
        amp = (1 / k ** 1.25) * (0.6 if k % 2 == 0 else 1)
        out += amp * np.sin(2 * np.pi * f * t + rng.uniform(0, 6.28)) * np.exp(-t * (1.6 + 1.1 * k))
    out *= np.minimum(1, t / 0.004)
    return out * vel * 0.32


def celesta(freq, dur, vel=1.0):
    n = int(dur * SR)
    t = np.arange(n) / SR
    partials = [(1, 1.0, 2.2), (2, 0.38, 3.5), (3, 0.14, 5.0), (4.2, 0.07, 7.0)]
    out = sum(a * np.sin(2 * np.pi * freq * m * t) * np.exp(-t * d) for m, a, d in partials)
    out *= np.minimum(1, t / 0.002)
    return out * vel * 0.22


def pad_chord(notes, dur, vel=1.0):
    """Warm string pad: detuned soft saws (band-limited) with slow attack."""
    n = int(dur * SR)
    t = np.arange(n) / SR
    out = np.zeros(n)
    for note in notes:
        for det in (-0.07, 0.0, 0.07):
            f = midi(note + det)
            vib = 1 + 0.0025 * np.sin(2 * np.pi * (4.8 + det) * t)
            ph = 2 * np.pi * f * np.cumsum(vib) / SR
            for k in range(1, 7):
                out += np.sin(k * ph) / k ** 1.8
    out *= env_adsr(n, 1.2, 0.5, 0.85, 1.3)
    return out * vel * 0.016


def bass(freq, dur, vel=1.0, pluck=False):
    n = int(dur * SR)
    t = np.arange(n) / SR
    if pluck:
        e = np.exp(-t * 5)
    else:
        e = env_adsr(n, 0.05, 0.3, 0.7, 0.4)
    out = (np.sin(2 * np.pi * freq * t) + 0.25 * np.sin(4 * np.pi * freq * t)) * e
    return out * vel * 0.2


def shaker(dur=0.09, vel=1.0):
    n = int(dur * SR)
    t = np.arange(n) / SR
    noise = rng.standard_normal(n)
    noise = np.diff(np.concatenate([[0], noise]))  # crude high-pass
    return noise * np.exp(-t * 55) * vel * 0.03


def soft_kick(vel=1.0):
    n = int(0.25 * SR)
    t = np.arange(n) / SR
    f = 120 * np.exp(-t * 18) + 45
    return np.sin(2 * np.pi * np.cumsum(f) / SR) * np.exp(-t * 14) * vel * 0.28


def place(buf, sig, start, pan=0.0):
    i = int(start * SR)
    j = min(len(buf), i + len(sig))
    if j <= i:
        return
    l, r = np.sqrt((1 - pan) / 2), np.sqrt((1 + pan) / 2)
    buf[i:j, 0] += sig[: j - i] * l
    buf[i:j, 1] += sig[: j - i] * r


def reverb(x, seconds=2.6, mix=0.32):
    n = int(seconds * SR)
    t = np.arange(n) / SR
    out = np.empty_like(x)
    for ch in range(2):
        ir = rng.standard_normal(n) * np.exp(-t / (seconds / 5.5))
        ir[: int(0.012 * SR)] = 0
        ir /= np.sqrt(np.sum(ir ** 2))
        size = 1 << int(np.ceil(np.log2(len(x) + n)))
        wet = np.fft.irfft(np.fft.rfft(x[:, ch], size) * np.fft.rfft(ir, size), size)[: len(x)]
        out[:, ch] = x[:, ch] * (1 - mix) + wet * mix * 1.6
    return out


def make_loop(render, length, path, peak_db=-7.0):
    tail = 3.5
    buf = np.zeros((int((length + tail) * SR), 2))
    render(buf)
    buf = reverb(buf)
    # Wrap the reverb tail to the start so the loop is seamless
    L = int(length * SR)
    loop = buf[:L].copy()
    loop[: len(buf) - L] += buf[L:]
    # Gentle low-pass for warmth
    a = 0.55
    for ch in range(2):
        y = loop[:, ch]
        z = np.empty_like(y)
        acc = 0.0
        # vectorised one-pole via lfilter-like cumulative trick is overkill; do a short FIR instead
        z = np.convolve(y, [0.25, 0.5, 0.25], mode='same')
        loop[:, ch] = z * a + y * (1 - a)
    loop /= np.max(np.abs(loop)) / (10 ** (peak_db / 20))
    pcm = (loop * 32767).astype(np.int16)
    subprocess.run(['ffmpeg', '-y', '-loglevel', 'error', '-f', 's16le', '-ar', str(SR), '-ac', '2', '-i', '-',
                    '-b:a', '96k', path], input=pcm.tobytes(), check=True)
    print(path, f'{length:.1f}s')


# ---------------- "Moonlit Court" (menu) ----------------
def menu(buf):
    bpm = 70
    beat = 60 / bpm
    bar = 4 * beat
    # D major: Dmaj9 | Bm9 | Gmaj7#11 | A6sus4 -> A
    prog = [
        (50, [62, 66, 69, 73, 76]),
        (47, [62, 66, 69, 71, 74]),
        (43, [62, 66, 67, 71, 73]),
        (45, [61, 64, 66, 69, 71]),
    ]
    melody_scale = [74, 76, 78, 81, 83, 86, 88]
    phrases = [
        [(0, 81, 1.5), (1.5, 78, 0.5), (2, 76, 1), (3, 78, 1)],
        [(0, 74, 2), (2, 78, 1), (3, 81, 1)],
        [(0, 83, 1.5), (1.5, 81, 0.5), (2, 78, 1.5), (3.5, 76, 0.5)],
        [(0, 78, 2), (2, 76, 1), (3, 73, 1)],
    ]
    for rep in range(4):
        for ci, (root, chord) in enumerate(prog):
            t0 = (rep * 4 + ci) * bar
            place(buf, pad_chord(chord[:4], bar + 1.2, 1.0), t0, 0)
            place(buf, bass(midi(root), bar), t0, 0)
            # Harp: rising and falling arpeggio in eighth notes
            arp = chord + [c + 12 for c in chord[:3]]
            pattern = [0, 1, 2, 3, 4, 5, 4, 2]
            for k, p in enumerate(pattern):
                place(buf, harp(midi(arp[p]), 2.6, 0.75 + 0.2 * (k == 0)), t0 + k * beat / 2, -0.35 + 0.1 * (k % 3))
            # Celesta melody on the 2nd and 4th pass
            if rep in (1, 3):
                for off, note, d in phrases[ci]:
                    place(buf, celesta(midi(note), 2.4, 0.9), t0 + off * beat, 0.35)
            elif rep == 2 and ci % 2 == 1:
                for k in range(3):
                    n = melody_scale[rng.integers(2, len(melody_scale))]
                    place(buf, celesta(midi(n + 12), 1.8, 0.35), t0 + (1.5 + k * 0.75) * beat, 0.6)


# ---------------- "Starlit Steps" (game) ----------------
def game(buf):
    bpm = 96
    beat = 60 / bpm
    bar = 4 * beat
    # A major: A | F#m7 | Dmaj7 | Esus4 -> E
    prog = [
        (45, [57, 61, 64, 69, 71]),
        (42, [57, 61, 64, 66, 69]),
        (38, [57, 61, 62, 66, 69]),
        (40, [56, 59, 64, 66, 71]),
    ]
    phrases = [
        [(0, 76, 0.5), (0.5, 78, 0.5), (1, 81, 1), (2, 80, 0.5), (2.5, 78, 0.5), (3, 76, 1)],
        [(0, 73, 1), (1, 76, 0.5), (1.5, 78, 0.5), (2, 81, 1.5), (3.5, 78, 0.5)],
        [(0, 78, 0.5), (0.5, 81, 0.5), (1, 85, 1), (2, 83, 1), (3, 81, 1)],
        [(0, 80, 1.5), (1.5, 78, 0.5), (2, 76, 1), (3, 71, 1)],
    ]
    for rep in range(4):
        for ci, (root, chord) in enumerate(prog):
            t0 = (rep * 4 + ci) * bar
            place(buf, pad_chord(chord[:4], bar + 0.8, 0.7), t0, 0)
            # Pizzicato bass: root, fifth, octave, fifth
            for k, iv in enumerate([0, 7, 12, 7]):
                place(buf, bass(midi(root + iv), beat * 0.9, 0.9, pluck=True), t0 + k * beat, 0)
            # Harp sixteenths
            arp = chord + [c + 12 for c in chord[:3]]
            pattern = [0, 2, 4, 6, 7, 6, 4, 2, 1, 3, 5, 7, 6, 5, 3, 1]
            for k, p in enumerate(pattern):
                place(buf, harp(midi(arp[p]), 1.6, 0.42 + 0.18 * (k % 4 == 0)), t0 + k * beat / 4, -0.4 + 0.05 * (k % 5))
            # Soft pulse from the 2nd pass on
            if rep >= 1:
                for k in range(4):
                    place(buf, soft_kick(0.55 if k % 2 == 0 else 0.3), t0 + k * beat, 0)
                for k in range(8):
                    place(buf, shaker(vel=1.0 if k % 2 else 0.5), t0 + k * beat / 2, 0.3)
            if rep in (1, 2, 3):
                for off, note, d in phrases[ci]:
                    place(buf, celesta(midi(note), 1.8, 0.8 if rep != 2 else 0.6), t0 + off * beat, 0.3)


if __name__ == '__main__':
    make_loop(menu, 16 * 4 * 60 / 70, 'www/audio/music-menu.mp3', peak_db=-14)
    make_loop(game, 16 * 4 * 60 / 96, 'www/audio/music-game.mp3', peak_db=-15)
